# Auto-generated by PyAPK Builder
# buildozer.spec — PyAPK Hello
# Optimized for stability + minimal APK size

[app]

# ── App metadata ──────────────────────────────────────────────
title = PyAPK Hello
package.name = helloapp
package.domain = com.anwar
source.dir = .
source.include_exts = py,png,jpg,jpeg,kv,atlas,ttf,txt,json,csv,wav,mp3,ogg,ini,cfg
version = 1.0.0
android.numeric_version = 1000000

# ── Python requirements (pinned for stability) ───────────────
requirements = python3,kivy

# ── Source exclusions (reduce APK size, prevent conflicts) ───
source.exclude_dirs = tests, test, __pycache__, .git, bin, .buildozer, build, dist, docs, .venv, venv, node_modules
source.exclude_patterns = *_test.py, *_test_*.py, conftest.py, setup.py, setup.cfg, tox.ini, pytest.ini, Makefile, Dockerfile

# ── Orientation ───────────────────────────────────────────────
orientation = portrait

# ── Permissions ───────────────────────────────────────────────
android.permissions = android.permission.INTERNET

# ── Android API levels (min 21 = Android 5.0, 95%+ coverage) ─
android.api = 34
android.minapi = 21
android.ndk = 25b

# ── Build settings ────────────────────────────────────────────
fullscreen = 0
android.archs = arm64-v8a
android.accept_sdk_license = True
android.allow_backup = False
android.copy_libs = 1
android.enable_androidx = True

# ── Release-specific optimizations ───────────────────────────
# (debug build — no release optimizations)

# ── Logging ───────────────────────────────────────────────────
log_level = 2
warn_on_root = 0
# Filter logcat to reduce noise — only show Python + errors
android.logcat_filters = *:S python:V SDL:V

# ── Presets / bootstrap ──────────────────────────────────────
p4a.bootstrap = sdl2
# Use the stable p4a version bundled in the Docker image (don't override branch)

# ── Prevent .pyc corruption on some devices ──────────────────
no-compile2pyc = False

# ── Entry point (sdl2 bootstrap uses org.kivy.android.PythonActivity) ─
android.entrypoint = org.kivy.android.PythonActivity

[buildozer]
log_level = 2
warn_on_root = 0
